from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.parsers import MultiPartParser, FormParser
from rest_framework.permissions import IsAuthenticated
from rest_framework import status
from django.http import HttpResponse
from .models import EquipmentData
from .serializers import EquipmentDataSerializer
import pandas as pd
from reportlab.pdfgen import canvas
import io

# 1. Upload & Analyze (Now Protected)
class UploadAnalyzeView(APIView):
    permission_classes = [IsAuthenticated] # <--- Requires Login
    parser_classes = (MultiPartParser, FormParser)

    def post(self, request, *args, **kwargs):
        file_serializer = EquipmentDataSerializer(data=request.data)
        if file_serializer.is_valid():
            file_obj = request.FILES['file']
            instance = file_serializer.save()

            try:
                file_obj.seek(0)
                df = pd.read_csv(file_obj)
                
                # Calculate Distribution
                if 'Type' in df.columns:
                    dist_counts = df['Type'].value_counts()
                    dist_dict = dist_counts.to_dict()
                    # Prepare lists for the Desktop App Chart
                    chart_labels = dist_counts.index.tolist()
                    chart_data = dist_counts.values.tolist()
                else:
                    dist_dict = {}
                    chart_labels = []
                    chart_data = []

                # Stats Dictionary
                stats = {
                    "total_count": len(df),  # Desktop looks for 'total_count'
                    "avg_pressure": round(df['Pressure'].mean(), 2) if 'Pressure' in df.columns else 0,
                    "avg_temp": round(df['Temperature'].mean(), 2) if 'Temperature' in df.columns else 0,
                    "type_distribution": dist_dict, # Keep for Web App
                    "chart_labels": chart_labels,   # Added for Desktop App
                    "chart_data": chart_data        # Added for Desktop App
                }

                return Response({
                    "message": "File processed",
                    "id": instance.id,
                    "stats": stats
                }, status=status.HTTP_201_CREATED)

            except Exception as e:
                return Response({"error": str(e)}, status=status.HTTP_400_BAD_REQUEST)
        
        return Response(file_serializer.errors, status=status.HTTP_400_BAD_REQUEST)

# 2. History View (Now Protected)
class HistoryView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        recent = EquipmentData.objects.all().order_by('-uploaded_at')[:5]
        # Changed 'date' to 'timestamp' to match Desktop App
        data = [{
            "id": i.id, 
            "filename": str(i.file).split('/')[-1], 
            "timestamp": i.uploaded_at.strftime("%Y-%m-%d %H:%M") 
        } for i in recent]
        return Response(data)

# 3. PDF Generation View
class GeneratePDFView(APIView):
    permission_classes = [IsAuthenticated] 

    def get(self, request):
        buffer = io.BytesIO()
        p = canvas.Canvas(buffer)

        p.setFont("Helvetica-Bold", 16)
        p.drawString(100, 800, "Chemical Equipment Analytics Report")
        
        p.setFont("Helvetica", 12)
        p.drawString(100, 780, "Generated by: Hybrid Chemical App")
        
        last_upload = EquipmentData.objects.last()
        if last_upload:
            p.drawString(100, 750, f"Latest File: {str(last_upload.file)}")
            p.drawString(100, 730, f"Uploaded At: {last_upload.uploaded_at}")
        else:
            p.drawString(100, 750, "No data available.")

        p.showPage()
        p.save()

        buffer.seek(0)
        return HttpResponse(buffer, content_type='application/pdf')